<?php

namespace Database\Seeders;

use App\Models\MockSubscriber;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

/**
 * Dedicated development & testing seeder for Mock Subscribers.
 * Clearly identified with contract prefix TEST-1000XX.
 * Strictly disabled in production.
 */
class MockSubscriberSeeder extends Seeder
{
    public function run(): void
    {
        if (app()->environment('production')) {
            return;
        }

        $now = Carbon::now();

        $subscribers = [
            // Scenario 1: Active, Normal package, Normal usage
            [
                'contract_number' => 'TEST-100001',
                'name' => 'خالد محمد عبد الله',
                'phone' => '0912345678',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-100',
                'current_package_name' => 'ميقا 100G',
                'current_package_price' => 100.00,
                'data_allowance_gb' => 100.00,
                'used_data_gb' => 35.50,
                'expires_at' => $now->copy()->addDays(18),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 2: Active, High usage, Low remaining quota (< 10%)
            [
                'contract_number' => 'TEST-100002',
                'name' => 'سالم مفتاح علي',
                'phone' => '0923456789',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-150',
                'current_package_name' => 'ميقا 150G',
                'current_package_price' => 150.00,
                'data_allowance_gb' => 150.00,
                'used_data_gb' => 142.30,
                'expires_at' => $now->copy()->addDays(4),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 3: Active, Nearly exhausted quota (99% used)
            [
                'contract_number' => 'TEST-100003',
                'name' => 'الهادي أحمد ربيض',
                'phone' => '0934567890',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-70',
                'current_package_name' => 'ميقا 70G',
                'current_package_price' => 70.00,
                'data_allowance_gb' => 79.00,
                'used_data_gb' => 78.50,
                'expires_at' => $now->copy()->addDays(2),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 4: Expired subscription (expired 5 days ago, 100% quota used)
            [
                'contract_number' => 'TEST-100004',
                'name' => 'عمر عبد اللطيف',
                'phone' => '0945678901',
                'status' => 'EXPIRED',
                'current_package_id' => 'PKG-70',
                'current_package_name' => 'ميقا 70G',
                'current_package_price' => 70.00,
                'data_allowance_gb' => 79.00,
                'used_data_gb' => 79.00,
                'expires_at' => $now->copy()->subDays(5),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 5: Suspended subscriber (cannot recharge or change package)
            [
                'contract_number' => 'TEST-100005',
                'name' => 'مروان السنوسي',
                'phone' => '0956789012',
                'status' => 'SUSPENDED',
                'current_package_id' => 'PKG-150',
                'current_package_name' => 'ميقا 150G',
                'current_package_price' => 150.00,
                'data_allowance_gb' => 150.00,
                'used_data_gb' => 150.00,
                'expires_at' => $now->copy()->subDays(15),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 6: Borrowing ACTIVE (emergency grace period in progress)
            [
                'contract_number' => 'TEST-100006',
                'name' => 'طارق الزوي',
                'phone' => '0967890123',
                'status' => 'EXPIRED',
                'current_package_id' => 'PKG-70',
                'current_package_name' => 'ميقا 70G',
                'current_package_price' => 70.00,
                'data_allowance_gb' => 79.00,
                'used_data_gb' => 79.00,
                'expires_at' => $now->copy()->subDays(3),
                'borrowing_status' => 'ACTIVE',
                'borrowing_used_gb' => 22.50,
                'borrowing_expires_at' => $now->copy()->addDays(2),
            ],
            // Scenario 7: Borrowing AVAILABLE (eligible to activate borrowing)
            [
                'contract_number' => 'TEST-100007',
                'name' => 'منيرة الفيتوري',
                'phone' => '0978901234',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-100',
                'current_package_name' => 'ميقا 100G',
                'current_package_price' => 100.00,
                'data_allowance_gb' => 100.00,
                'used_data_gb' => 96.00,
                'expires_at' => $now->copy()->addDays(1),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 8: Borrowing EXPIRED (grace period expired, debt unpaid)
            [
                'contract_number' => 'TEST-100008',
                'name' => 'فاطمة عبد السلام',
                'phone' => '0911223344',
                'status' => 'EXPIRED',
                'current_package_id' => 'PKG-150',
                'current_package_name' => 'ميقا 150G',
                'current_package_price' => 150.00,
                'data_allowance_gb' => 150.00,
                'used_data_gb' => 150.00,
                'expires_at' => $now->copy()->subDays(10),
                'borrowing_status' => 'EXPIRED',
                'borrowing_used_gb' => 70.00,
                'borrowing_expires_at' => $now->copy()->subDays(3),
            ],
            // Scenario 9: Recently recharged (0% used, 30 days left)
            [
                'contract_number' => 'TEST-100009',
                'name' => 'مصطفى قاسم',
                'phone' => '0922334455',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-300',
                'current_package_name' => 'ميقا 300G',
                'current_package_price' => 300.00,
                'data_allowance_gb' => 300.00,
                'used_data_gb' => 0.00,
                'expires_at' => $now->copy()->addDays(30),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 10: High-Speed tier (PKG-500)
            [
                'contract_number' => 'TEST-100010',
                'name' => 'إبراهيم المبروك',
                'phone' => '0933445566',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-500',
                'current_package_name' => 'ميقا 500G',
                'current_package_price' => 500.00,
                'data_allowance_gb' => 500.00,
                'used_data_gb' => 125.00,
                'expires_at' => $now->copy()->addDays(22),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 11: Edge-case - missing optional phone
            [
                'contract_number' => 'TEST-100011',
                'name' => 'عائشة التاورغي',
                'phone' => null,
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-100',
                'current_package_name' => 'ميقا 100G',
                'current_package_price' => 100.00,
                'data_allowance_gb' => 100.00,
                'used_data_gb' => 55.40,
                'expires_at' => $now->copy()->addDays(14),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 12: Active moderate usage
            [
                'contract_number' => 'TEST-100012',
                'name' => 'يوسف الورفلي',
                'phone' => '0915566778',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-70',
                'current_package_name' => 'ميقا 70G',
                'current_package_price' => 70.00,
                'data_allowance_gb' => 79.00,
                'used_data_gb' => 45.00,
                'expires_at' => $now->copy()->addDays(10),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 13: Active enterprise tier
            [
                'contract_number' => 'TEST-100013',
                'name' => 'شركة النخبة للتقنية',
                'phone' => '0928899001',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-500',
                'current_package_name' => 'ميقا 500G',
                'current_package_price' => 500.00,
                'data_allowance_gb' => 500.00,
                'used_data_gb' => 410.00,
                'expires_at' => $now->copy()->addDays(7),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 14: Expired yesterday
            [
                'contract_number' => 'TEST-100014',
                'name' => 'نور الهدى الشريف',
                'phone' => '0937788990',
                'status' => 'EXPIRED',
                'current_package_id' => 'PKG-100',
                'current_package_name' => 'ميقا 100G',
                'current_package_price' => 100.00,
                'data_allowance_gb' => 100.00,
                'used_data_gb' => 100.00,
                'expires_at' => $now->copy()->subDay(),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 15: Active low usage
            [
                'contract_number' => 'TEST-100015',
                'name' => 'عبد الرحمن الدرسي',
                'phone' => '0941122334',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-150',
                'current_package_name' => 'ميقا 150G',
                'current_package_price' => 150.00,
                'data_allowance_gb' => 150.00,
                'used_data_gb' => 22.00,
                'expires_at' => $now->copy()->addDays(26),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 16: Suspended long term
            [
                'contract_number' => 'TEST-100016',
                'name' => 'عادل المقريف',
                'phone' => '0952233445',
                'status' => 'SUSPENDED',
                'current_package_id' => 'PKG-70',
                'current_package_name' => 'ميقا 70G',
                'current_package_price' => 70.00,
                'data_allowance_gb' => 79.00,
                'used_data_gb' => 79.00,
                'expires_at' => $now->copy()->subDays(60),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 17: Active 300G
            [
                'contract_number' => 'TEST-100017',
                'name' => 'زينب القاضي',
                'phone' => '0919988776',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-300',
                'current_package_name' => 'ميقا 300G',
                'current_package_price' => 300.00,
                'data_allowance_gb' => 300.00,
                'used_data_gb' => 115.00,
                'expires_at' => $now->copy()->addDays(19),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 18: Active nearly expired
            [
                'contract_number' => 'TEST-100018',
                'name' => 'فريد العريبي',
                'phone' => '0926677889',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-100',
                'current_package_name' => 'ميقا 100G',
                'current_package_price' => 100.00,
                'data_allowance_gb' => 100.00,
                'used_data_gb' => 88.00,
                'expires_at' => $now->copy()->addHours(12),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 19: Active 70G high speed
            [
                'contract_number' => 'TEST-100019',
                'name' => 'حنان المجبري',
                'phone' => '0935544332',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-70',
                'current_package_name' => 'ميقا 70G',
                'current_package_price' => 70.00,
                'data_allowance_gb' => 79.00,
                'used_data_gb' => 10.00,
                'expires_at' => $now->copy()->addDays(29),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 20: Expired 20 days ago
            [
                'contract_number' => 'TEST-100020',
                'name' => 'جمال بن يونس',
                'phone' => '0948877665',
                'status' => 'EXPIRED',
                'current_package_id' => 'PKG-150',
                'current_package_name' => 'ميقا 150G',
                'current_package_price' => 150.00,
                'data_allowance_gb' => 150.00,
                'used_data_gb' => 150.00,
                'expires_at' => $now->copy()->subDays(20),
                'borrowing_status' => 'AVAILABLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 21: Active 500G
            [
                'contract_number' => 'TEST-100021',
                'name' => 'مجمع الشفاء الطبي',
                'phone' => '0910011223',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-500',
                'current_package_name' => 'ميقا 500G',
                'current_package_price' => 500.00,
                'data_allowance_gb' => 500.00,
                'used_data_gb' => 200.00,
                'expires_at' => $now->copy()->addDays(15),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 22: Active 300G
            [
                'contract_number' => 'TEST-100022',
                'name' => 'صلاح الدين بازامة',
                'phone' => '0921133557',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-300',
                'current_package_name' => 'ميقا 300G',
                'current_package_price' => 300.00,
                'data_allowance_gb' => 300.00,
                'used_data_gb' => 180.00,
                'expires_at' => $now->copy()->addDays(11),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 23: Active 150G
            [
                'contract_number' => 'TEST-100023',
                'name' => 'ريم الصادق',
                'phone' => '0932244668',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-150',
                'current_package_name' => 'ميقا 150G',
                'current_package_price' => 150.00,
                'data_allowance_gb' => 150.00,
                'used_data_gb' => 75.00,
                'expires_at' => $now->copy()->addDays(16),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 24: Active 100G
            [
                'contract_number' => 'TEST-100024',
                'name' => 'وليد الغرياني',
                'phone' => '0943355779',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-100',
                'current_package_name' => 'ميقا 100G',
                'current_package_price' => 100.00,
                'data_allowance_gb' => 100.00,
                'used_data_gb' => 62.00,
                'expires_at' => $now->copy()->addDays(8),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
            // Scenario 25: Active 70G
            [
                'contract_number' => 'TEST-100025',
                'name' => 'هدى المنصوري',
                'phone' => '0954466880',
                'status' => 'ACTIVE',
                'current_package_id' => 'PKG-70',
                'current_package_name' => 'ميقا 70G',
                'current_package_price' => 70.00,
                'data_allowance_gb' => 79.00,
                'used_data_gb' => 18.00,
                'expires_at' => $now->copy()->addDays(24),
                'borrowing_status' => 'NOT_ELIGIBLE',
                'borrowing_used_gb' => 0.00,
                'borrowing_expires_at' => null,
            ],
        ];

        foreach ($subscribers as $data) {
            MockSubscriber::updateOrCreate(
                ['contract_number' => $data['contract_number']],
                $data,
            );
        }
    }
}
